language: node_js
node_js:
  - "10"
  - "9"
  - "8"
before_script:
  - npm install codecov -g
  - npm run bootstrap
  - npm run build
  - npm run bootstrap
after_success:
  - codecov
script: npm run test-ci
cache:
  directories:
    - "node_modules"